# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .random import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_pk_provider.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_pk_provider.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pk-provider",
  "mod": "index",
  "fqn": "pulumi_pk_provider",
  "classes": {
   "pk-provider:index:Random": "Random"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pk-provider",
  "token": "pulumi:providers:pk-provider",
  "fqn": "pulumi_pk_provider",
  "class": "Provider"
 }
]
"""
)
